### ISSUE TITLE
error

### ISSUE THREAD

**Issue by OlevO1** [Amaru8/CiderGTA#1]
yo! it's not working. This is the ScriptHookVDotNet log:

```
[11:43:55] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[11:43:55] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[11:43:55] [DEBUG] Loading scripts from C:\Program Files\Epic Games\GTAV\scripts ...
[11:43:55] [DEBUG] Loading assembly CiderGTA.dll ...
[11:43:55] [INFO] Found 1 script(s) in CiderGTA.dll resolved to API 3.6.0.
[11:43:55] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
[11:43:55] [INFO] Found 0 script(s) in LemonUI.SHVDN3.dll.
[11:43:55] [DEBUG] Instantiating script CiderGTA.CiderRadio ...
[11:43:56] [ERROR] Failed to instantiate script CiderGTA.CiderRadio because constructor threw an exception: System.TypeInitializationException: The type initializer for 'SHVDN.NativeMemory' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SHVDN.NativeMemory..cctor()
   --- End of inner exception stack trace ---
   at SHVDN.NativeMemory.StringToCoTaskMemUTF8(String s)
   at SHVDN.ScriptDomain.PinString(String str)
   at CiderGTA.CiderRadio..ctor()

```

cider mod log: 

![image](https://github.com/user-attachments/assets/2115a2ce-87d2-4998-b616-39105d495701)

![image](https://github.com/user-attachments/assets/fd2c5db6-63fa-4d31-acc0-567c91ad4a50)

![image](https://github.com/user-attachments/assets/33d6111d-4dc1-4c11-bd49-e0f9594f6e4d)

they only talk on the cider radio. please help me

**Comment by Amaru8** [comment]
Hey~
Please verify you are using the [latest version of ScriptHookVDotNet](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/latest).
Thanks!

**Comment by OlevO1** [comment]
it works now thank you
